version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    environment:
      - BACKEND_CORS_ORIGINS=["http://localhost:5173"]